services:
  - type: web
    name: aetheris-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python3 database_setup.py"
    startCommand: "python3 aetheris_bot.py"
